title: Babak Mammadov |  Kubernetes, Aws, Azure, Golang  & Cloud Native
description: Kubernetes, Aws, Azure, Golang, Cloud Native
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "verticaio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Babak Mammadov # add your name
author-img: bio-photo.jpg # add your photo
about-author: Focus on cloud-native application architectures and Software Development with Golang using container technologies on Cloud # add description
social-twitter: verticaio # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: verticaio # add your Github handle
social-linkedin: verticaio # add your Linkedin handle
social-telegram: verticaio

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-168839483-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "Gemfile", "Gemfile.lock", "README.md"]
